title: "Haque Abul Ahsan Md Mahmudul"
description: "Senior IT-arkitekt — personal profile"
# Use Minima as a remote theme (pin to a known ref for stability):
plugins:
  - jekyll-remote-theme
remote_theme: jekyll/minima@1e8a445

# Choose a skin (classic | dark | auto | solarized-light | solarized-dark)
minima:
  skin: classic
  nav_pages:
    - about.md
    - projects.md
    - resume.md
    - contact.md


url: "https://abul-haque.github.io"
baseurl: ""
url: "https://abul-haque.github.io"
baseurl: "/profile"
``
